packages:
  - sdk
  - cli

blockExoticSubdeps: true
catalogMode: strict
cleanupUnusedCatalogs: true
minimumReleaseAge: 10080
packageManagerStrictVersion: true
trustPolicy: no-downgrade
updateNotifier: false
verifyDepsBeforeRun: warn
